package vn.netstars.addin.imedia.topup.utils

import com.blankj.utilcode.util.CacheDiskUtils
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import vn.netstars.addin.imedia.topup.datasource.model.CardItem

object FakeDataUtils {

    const val CARD_ITEM = "card_item"

//    fun initFakeData(): ArrayList<CardItem> {
//        val listCardItem = ArrayList<CardItem>()
//        //Viettel
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Viettel",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Viettel",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Viettel",
//                30000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Viettel",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Viettel",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Viettel",
//                300000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Viettel",
//                500000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Viettel",
//                1000000
//            )
//        )
//
//        //Vinaphone
//        listCardItem.add(
//            CardItem(
//                1,
//                2,
//                "Vinaphone",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                2,
//                "Vinaphone",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                2,
//                "Vinaphone",
//                30000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                2,
//                "Vinaphone",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                2,
//                "Vinaphone",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                2,
//                "Vinaphone",
//                300000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                2,
//                "Vinaphone",
//                500000
//            )
//        )
////        listCardItem.add(CardItem(1,2, "Vinaphone", 1000000))
//
//        //Mobiphone
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Mobiphone",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Mobiphone",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Mobiphone",
//                30000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Mobiphone",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Mobiphone",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Mobiphone",
//                300000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Mobiphone",
//                500000
//            )
//        )
////        listCardItem.add(CardItem(1,3, "Mobiphone", 1000000))
//
//        //Beeline
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Beeline",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Beeline",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Beeline",
//                30000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Beeline",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Beeline",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Beeline",
//                300000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                3,
//                "Beeline",
//                500000
//            )
//        )
////        listCardItem.add(CardItem(1, 3, "Beeline", 1000000))
//
//        //vnmobile
//        listCardItem.add(
//            CardItem(
//                1,
//                4,
//                "Vnmobile",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                4,
//                "Vnmobile",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                4,
//                "Vnmobile",
//                30000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                4,
//                "Vnmobile",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                4,
//                "Vnmobile",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                4,
//                "Vnmobile",
//                300000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                4,
//                "Vnmobile",
//                500000
//            )
//        )
////        listCardItem.add(CardItem(1, 4, "Vnmobile", 100000))
//
//        //Vcoin
//        listCardItem.add(
//            CardItem(
//                1,
//                5,
//                "VCOIN",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                5,
//                "VCOIN",
//                20000
//            )
//        )
//        //listCardItem.add(CardItem(1,1, "Viettel", 30000))
//        listCardItem.add(
//            CardItem(
//                1,
//                5,
//                "VCOIN",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                5,
//                "VCOIN",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                5,
//                "VCOIN",
//                300000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                5,
//                "VCOIN",
//                500000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                5,
//                "VCOIN",
//                1000000
//            )
//        )
//
//        //Gate
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                30000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                60000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                90000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                200000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                300000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                500000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                1000000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                2000000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Gate",
//                5000000
//            )
//        )
//
//        //Zing
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                300000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                500000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                1000000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                2000000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "ZingCard",
//                5000000
//            )
//        )
//
//        //Garena
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Garena",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Garena",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Garena",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Garena",
//                200000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "Garena",
//                500000
//            )
//        )
//
//        //OnCashDN
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "OnCashDN",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "OnCashDN",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "OnCashDN",
//                30000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "OnCashDN",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "OnCashDN",
//                60000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "OnCashDN",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "OnCashDN",
//                200000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "OnCashDN",
//                500000
//            )
//        )
//
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                200000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                500000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                1000000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                2000000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "BIT",
//                5000000
//            )
//        )
//
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVNP",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVNP",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVNP",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVNP",
//                70000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVNP",
//                100000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVNP",
//                120000
//            )
//        )
//
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVTT",
//                5000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVTT",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVTT",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVTT",
//                100000
//            )
//        )
//
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                1000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                2000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                3000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                5000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                10000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                14000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                20000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                28000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                30000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                42000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                50000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                56000
//            )
//        )
//        listCardItem.add(
//            CardItem(
//                1,
//                1,
//                "DataVMS",
//                84000
//            )
//        )
//
//        return listCardItem
//    }

    fun saveListCard(listQrInfo: ArrayList<CardItem>) {
        if (listQrInfo.size == 0) return
        CacheDiskUtils.getInstance().apply {
            put(
                CARD_ITEM, Gson().toJson(listQrInfo)
            )
        }
    }

    fun getListCard(): ArrayList<CardItem> {
        val jsonQrInfo = CacheDiskUtils.getInstance().getString(CARD_ITEM, null)
        jsonQrInfo?.let {
            val type = object : TypeToken<ArrayList<CardItem>>() {}.type
            return Gson().fromJson(it, type)
        }
        return arrayListOf()
    }
}